import Aura from '@primeuix/themes/aura'
import { definePreset } from '@primeuix/themes'
import tailwindcss from '@tailwindcss/vite'

const formControlRoot = {
  background: '{form.field.background}',
  filledBackground: '{form.field.filled.background}',
  filledHoverBackground: '{form.field.filled.hover.background}',
  filledFocusBackground: '{form.field.filled.focus.background}',
  borderColor: '{form.field.border.color}',
  hoverBorderColor: '{form.field.hover.border.color}',
  focusBorderColor: '{form.field.focus.border.color}',
  color: '{form.field.color}',
  placeholderColor: '{form.field.placeholder.color}',
  shadow: '{form.field.shadow}',
  paddingX: '{form.field.padding.x}',
  paddingY: '{form.field.padding.y}',
  borderRadius: '{form.field.border.radius}',
  focusRing: {
    width: '{form.field.focus.ring.width}',
    style: '{form.field.focus.ring.style}',
    color: '{form.field.focus.ring.color}',
    offset: '{form.field.focus.ring.offset}',
    shadow: '{form.field.focus.ring.shadow}',
  },
}

const overlaySelectTokens = {
  overlay: {
    background: '{overlay.select.background}',
    borderColor: '{overlay.select.border.color}',
    borderRadius: '{overlay.select.border.radius}',
    color: '{overlay.select.color}',
    shadow: '{overlay.select.shadow}',
  },
  list: {
    padding: '{list.padding}',
    gap: '{list.gap}',
  },
  option: {
    focusBackground: '{list.option.focus.background}',
    selectedBackground: '{list.option.selected.background}',
    selectedFocusBackground: '{list.option.selected.focus.background}',
    color: '{list.option.color}',
    focusColor: '{list.option.focus.color}',
    selectedColor: '{list.option.selected.color}',
    selectedFocusColor: '{list.option.selected.focus.color}',
    padding: '{list.option.padding}',
    borderRadius: '{list.option.border.radius}',
  },
}

const optionControlFocusRing = {
  width: '4px',
  style: 'solid',
  color: 'rgba(11, 152, 47, 0.12)',
  offset: '0',
  shadow: 'none',
}

const NexaPrimePreset = definePreset(Aura, {
  semantic: {
    primary: {
      50: '#e8f6ee',
      100: '#ccebd8',
      200: '#98d3b0',
      300: '#74d28f',
      400: '#2fb452',
      500: '#0b982f',
      600: '#087a28',
      700: '#066322',
      800: '#022c14',
      900: '#021f0f',
      950: '#011408',
    },
    formField: {
      paddingX: '0.875rem',
      paddingY: '0.625rem',
      borderRadius: '12px',
      focusRing: optionControlFocusRing,
      transitionDuration: '0.16s',
    },
    list: {
      padding: '0.35rem',
      gap: '0.125rem',
      option: {
        padding: '0.65rem 0.75rem',
        borderRadius: '9px',
      },
    },
    overlay: {
      select: {
        borderRadius: '12px',
        shadow: '0 18px 42px rgba(15, 23, 42, 0.12)',
      },
    },
    colorScheme: {
      light: {
        formField: {
          background: '#ffffff',
          filledBackground: '#ffffff',
          filledHoverBackground: '#ffffff',
          filledFocusBackground: '#ffffff',
          borderColor: '#dce5df',
          hoverBorderColor: '#b9d0c1',
          focusBorderColor: '#0b982f',
          color: '#0b1f3a',
          placeholderColor: '#8b9a90',
          iconColor: '#41617f',
          shadow: 'none',
        },
        overlay: {
          select: {
            background: '#ffffff',
            borderColor: '#dce5df',
            color: '#0b1f3a',
          },
        },
        list: {
          option: {
            focusBackground: '#f1f8f3',
            selectedBackground: '#eaf6e7',
            selectedFocusBackground: '#d8efd0',
            color: '#0b1f3a',
            focusColor: '#0b1f3a',
            selectedColor: '#0a6f1f',
            selectedFocusColor: '#0a6f1f',
          },
        },
      },
    },
  },
  components: {
    inputtext: {
      root: formControlRoot,
    },
    textarea: {
      root: {
        ...formControlRoot,
        paddingY: '0.75rem',
      },
    },
    select: {
      root: formControlRoot,
      dropdown: {
        width: '2.75rem',
        color: '#41617f',
      },
      ...overlaySelectTokens,
    },
    multiselect: {
      root: formControlRoot,
      dropdown: {
        width: '2.75rem',
        color: '#41617f',
      },
      ...overlaySelectTokens,
      option: {
        ...overlaySelectTokens.option,
        gap: '0.625rem',
      },
      chip: {
        borderRadius: '8px',
      },
    },
    autocomplete: {
      root: formControlRoot,
      dropdown: {
        width: '2.75rem',
        borderColor: '#dce5df',
        hoverBorderColor: '#b9d0c1',
        activeBorderColor: '#0b982f',
        borderRadius: '0 12px 12px 0',
        background: '#f1f8f3',
        hoverBackground: '#eaf6e7',
        activeBackground: '#d8efd0',
        color: '#087a28',
        hoverColor: '#087a28',
        activeColor: '#087a28',
        focusRing: optionControlFocusRing,
      },
      ...overlaySelectTokens,
      chip: {
        borderRadius: '8px',
        focusBackground: '#eaf6e7',
        focusColor: '#0a6f1f',
      },
    },
    datepicker: {
      dropdown: {
        width: '2.75rem',
        borderColor: '#dce5df',
        hoverBorderColor: '#b9d0c1',
        activeBorderColor: '#0b982f',
        borderRadius: '0 12px 12px 0',
        background: '#f1f8f3',
        hoverBackground: '#eaf6e7',
        activeBackground: '#d8efd0',
        color: '#087a28',
        hoverColor: '#087a28',
        activeColor: '#087a28',
        focusRing: optionControlFocusRing,
      },
      panel: {
        background: '#ffffff',
        borderColor: '#dce5df',
        color: '#0b1f3a',
        borderRadius: '12px',
        shadow: '0 18px 42px rgba(15, 23, 42, 0.12)',
        padding: '0.5rem',
      },
      date: {
        hoverBackground: '#f1f8f3',
        selectedBackground: '#0b982f',
        rangeSelectedBackground: '#eaf6e7',
        color: '#0b1f3a',
        hoverColor: '#0b1f3a',
        selectedColor: '#ffffff',
        rangeSelectedColor: '#0a6f1f',
        borderRadius: '9px',
        focusRing: optionControlFocusRing,
      },
    },
    inputnumber: {
      button: {
        width: '2.75rem',
        borderRadius: '10px',
        background: '#f1f8f3',
        hoverBackground: '#eaf6e7',
        activeBackground: '#d8efd0',
        borderColor: '#dce5df',
        hoverBorderColor: '#b9d0c1',
        activeBorderColor: '#0b982f',
        color: '#087a28',
        hoverColor: '#087a28',
        activeColor: '#087a28',
      },
    },
    checkbox: {
      root: {
        borderRadius: '7px',
        width: '1.125rem',
        height: '1.125rem',
        background: '#ffffff',
        checkedBackground: '#0b982f',
        checkedHoverBackground: '#087a28',
        filledBackground: '#ffffff',
        borderColor: '#dce5df',
        hoverBorderColor: '#b9d0c1',
        focusBorderColor: '#0b982f',
        checkedBorderColor: '#0b982f',
        checkedHoverBorderColor: '#087a28',
        checkedFocusBorderColor: '#0b982f',
        shadow: 'none',
        focusRing: optionControlFocusRing,
      },
      icon: {
        checkedColor: '#ffffff',
        checkedHoverColor: '#ffffff',
      },
    },
    radiobutton: {
      root: {
        width: '1.125rem',
        height: '1.125rem',
        background: '#ffffff',
        checkedBackground: '#0b982f',
        checkedHoverBackground: '#087a28',
        filledBackground: '#ffffff',
        borderColor: '#dce5df',
        hoverBorderColor: '#b9d0c1',
        focusBorderColor: '#0b982f',
        checkedBorderColor: '#0b982f',
        checkedHoverBorderColor: '#087a28',
        checkedFocusBorderColor: '#0b982f',
        shadow: 'none',
        focusRing: optionControlFocusRing,
      },
      icon: {
        checkedColor: '#ffffff',
        checkedHoverColor: '#ffffff',
      },
    },
    toggleswitch: {
      root: {
        borderColor: '#dce5df',
        hoverBorderColor: '#b9d0c1',
        checkedBorderColor: '#0b982f',
        checkedHoverBorderColor: '#087a28',
        background: '#e7eee8',
        hoverBackground: '#dce5df',
        checkedBackground: '#0b982f',
        checkedHoverBackground: '#087a28',
        shadow: 'none',
        focusRing: optionControlFocusRing,
      },
      handle: {
        background: '#ffffff',
        hoverBackground: '#ffffff',
        checkedBackground: '#ffffff',
        checkedHoverBackground: '#ffffff',
      },
    },
    selectbutton: {
      root: {
        borderRadius: '12px',
      },
    },
    password: {
      icon: {
        color: '#41617f',
      },
      overlay: {
        background: '#ffffff',
        borderColor: '#dce5df',
        borderRadius: '12px',
        color: '#0b1f3a',
        shadow: '0 18px 42px rgba(15, 23, 42, 0.12)',
      },
    },
  },
})

const NexaPrimeLocale = {
  startsWith: 'Empieza con',
  contains: 'Contiene',
  notContains: 'No contiene',
  endsWith: 'Termina con',
  equals: 'Igual a',
  notEquals: 'Diferente de',
  noFilter: 'Sin filtro',
  lt: 'Menor que',
  lte: 'Menor o igual que',
  gt: 'Mayor que',
  gte: 'Mayor o igual que',
  dateIs: 'La fecha es',
  dateIsNot: 'La fecha no es',
  dateBefore: 'Fecha antes de',
  dateAfter: 'Fecha después de',
  clear: 'Limpiar',
  apply: 'Aplicar',
  matchAll: 'Coincidir todo',
  matchAny: 'Coincidir cualquiera',
  addRule: 'Agregar regla',
  removeRule: 'Quitar regla',
  accept: 'Aceptar',
  reject: 'Cancelar',
  choose: 'Elegir',
  upload: 'Subir',
  cancel: 'Cancelar',
  completed: 'Completado',
  pending: 'Pendiente',
  fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
  dayNames: ['domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado'],
  dayNamesShort: ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'],
  dayNamesMin: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
  monthNames: [
    'enero',
    'febrero',
    'marzo',
    'abril',
    'mayo',
    'junio',
    'julio',
    'agosto',
    'septiembre',
    'octubre',
    'noviembre',
    'diciembre',
  ],
  monthNamesShort: ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'],
  chooseYear: 'Elegir año',
  chooseMonth: 'Elegir mes',
  chooseDate: 'Elegir fecha',
  prevDecade: 'Década anterior',
  nextDecade: 'Década siguiente',
  prevYear: 'Año anterior',
  nextYear: 'Año siguiente',
  prevMonth: 'Mes anterior',
  nextMonth: 'Mes siguiente',
  prevHour: 'Hora anterior',
  nextHour: 'Hora siguiente',
  prevMinute: 'Minuto anterior',
  nextMinute: 'Minuto siguiente',
  prevSecond: 'Segundo anterior',
  nextSecond: 'Segundo siguiente',
  am: 'a. m.',
  pm: 'p. m.',
  today: 'Hoy',
  weekHeader: 'Sem',
  firstDayOfWeek: 1,
  showMonthAfterYear: false,
  dateFormat: 'dd/mm/yy',
  weak: 'Débil',
  medium: 'Media',
  strong: 'Fuerte',
  passwordPrompt: 'Ingresa una contraseña',
  searchMessage: '{0} resultados disponibles',
  selectionMessage: '{0} elementos seleccionados',
  emptySelectionMessage: 'Sin elementos seleccionados',
  emptySearchMessage: 'No se encontraron resultados',
  fileChosenMessage: '{0} archivos',
  noFileChosenMessage: 'Ningún archivo seleccionado',
  emptyMessage: 'Sin opciones disponibles',
  aria: {
    trueLabel: 'Verdadero',
    falseLabel: 'Falso',
    nullLabel: 'No seleccionado',
    star: '1 estrella',
    stars: '{star} estrellas',
    selectAll: 'Todos los elementos seleccionados',
    unselectAll: 'Todos los elementos deseleccionados',
    close: 'Cerrar',
    previous: 'Anterior',
    next: 'Siguiente',
    navigation: 'Navegación',
    scrollTop: 'Subir al inicio',
    moveTop: 'Mover al inicio',
    moveUp: 'Mover arriba',
    moveDown: 'Mover abajo',
    moveBottom: 'Mover al final',
    moveToTarget: 'Mover al destino',
    moveToSource: 'Mover al origen',
    moveAllToTarget: 'Mover todo al destino',
    moveAllToSource: 'Mover todo al origen',
    pageLabel: 'Página {page}',
    firstPageLabel: 'Primera página',
    lastPageLabel: 'Última página',
    nextPageLabel: 'Página siguiente',
    prevPageLabel: 'Página anterior',
    rowsPerPageLabel: 'Filas por página',
    jumpToPageDropdownLabel: 'Ir a página',
    jumpToPageInputLabel: 'Ingresar página',
  },
}

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    '@nuxt/icon',
    '@primevue/nuxt-module',
  ],
  icon: {
    // Evita que Nitro empaquete colecciones Iconify enormes durante el build en Vercel.
    serverBundle: 'remote',
  },
  css: [
    '~/assets/css/main.css',
    'primeicons/primeicons.css',
  ],
  devtools: { enabled: true },
  compatibilityDate: '2024-04-03',
  app: {
    head: {
      htmlAttrs: { lang: 'es' },
      title: 'NEXA — IA para hacer crecer tu negocio | Cobija, Pando',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        {
          name: 'description',
          content:
            'NEXA es tu asistente inteligente que te ayuda a vender más, atraer clientes y poner precios justos. Hecho en la Amazonía boliviana.',
        },
        { name: 'theme-color', content: '#0b982f' },
      ],
      link: [
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        {
          rel: 'stylesheet',
          href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@500;600;700;800&display=swap',
        },
      ],
    },
  },
  sourcemap: {
    server: false,
    client: false,
  },
  primevue: {
    options: {
      ripple: true,
      inputVariant: 'filled',
      locale: NexaPrimeLocale,
      theme: {
        preset: NexaPrimePreset,
        options: {
          prefix: 'p',
          darkModeSelector: 'light',
          cssLayer: false,
        },
      },
    },
  },
  vite: {
    build: {
      sourcemap: false,
    },
    plugins: [
      tailwindcss(),
    ],
    optimizeDeps: {
      // Pre-bundle de devtools para evitar recargas completas en desarrollo.
      include: [
        '@vue/devtools-core',
        '@vue/devtools-kit',
      ],
    },
  },
})
